### ISSUE TITLE
Which library was Funsuite in?

### ISSUE THREAD

**Issue by dimashchepin** [Deseao/score-names#1]
https://github.com/Deseao/score-names/blob/02474ca748c5451527452b301746cf9d6827cd5d/src/main/test/scala/score/ScoreTest.scala#L1

**Comment by dimashchepin** [comment]
Because there are no dependencies listed in build.sbt, so I could not find which exact library/version should be used to get Funsuite...

**Comment by dimashchepin** [comment]
looks like it works if build.sbt has this line:
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % Test

**Comment by Deseao** [comment]
Oh odd, I thought that the build.sbt would be automatically updated by sbt. I think perhaps the VSCode Scala plugin was running something called Metals which prevented that from happening.
